name: CI

# Controls when the action will run.
on:
  push:
    branches:
      - release/*
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a one job
  update:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2

      # Install HackMyResume
      - name: Install HackMyResume
        run: npm install hacksalot/hackmyresume#dev -g

      # Install WeasyPrint
      - name: Install WeasyPrint
        run: |
          brew install python3 cairo pango gdk-pixbuf libffi
          pip3 install WeasyPrint

      # Install required fonts
      - name: Install Non-Free Fonts
        run: |
          brew tap colindean/fonts-nonfree
          brew install --cask font-microsoft-office
          brew tap homebrew/cask-fonts
          brew install --cask font-fontawesome
          sudo atsutil databases -remove
          atsutil server -shutdown
          atsutil server -ping
          fc-list

      # Check-out sadeh theme repo
      - uses: actions/checkout@v4.1.1
        with:
          repository: nekofar/fresh-theme-sadeh
          ref: develop
          path: sadeh

      # Check-out markdown theme repo
      - uses: actions/checkout@v4.1.1
        with:
          repository: nekofar/fresh-theme-markdown
          ref: develop
          path: markdown

      # Checks-out resume repo
      - uses: actions/checkout@v4.1.1
        with:
          lfs: true
          path: resume

      # Generate resume file formats
      - name: Generate resume formats
        run: |
          hackmyresume build resume/resume.json to resume/readme.md -d -t markdown 
          hackmyresume build resume/resume.json to resume/resume.pdf -d -t sadeh -o resume/.hackmyrc.json -p weasyprint

      # Add & Commit resume changes
      - name: Add & Commit resume changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          cwd: resume
          add: resume.pdf readme.md
          message: "chore(resume): update resume files"
