# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: 
      - master
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a one job
  update:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
    # Setup Node.js environment
    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      
    # Install the latest version of HackMyResume with NPM:
    - name: Install HackMyResume with NPM
      run: npm install hacksalot/hackmyresume#dev -g
    
    # Install latest version of wkhtmltopdf & wkhtmltoimage
    # - name: Install wkhtmltopdf & wkhtmltoimage
      # run: |
        # brew cask install wkhtmltopdf
        # wkhtmltopdf --version
        # wkhtmltoimage --version
        
    # Install PhantomJS using Homebrew
    - name: Install PhantomJS 
      run: |
        brew cask install phantomjs
        phantomjs --version
    
    # Install Non-Free Fonts using Homebrew
    - name: Install Non-Free Fonts
      run: |
        brew tap colindean/fonts-nonfree
        brew cask install font-microsoft-office
        sudo atsutil databases -remove
        atsutil server -shutdown
        atsutil server -ping
  
    # Check-out themes repo
    - uses: actions/checkout@v2
      with:
        repository: nekofar/fresh-themes
        ref: develop
        path: fresh
    
    # Checks-out resume repo 
    - uses: actions/checkout@v2
      with:
        path: resume

    # Generate resume formats using HackMyResume
    - name: Generate resume formats
      run: |
        hackmyresume build resume/resume.json to resume/readme.txt -t fresh/themes/compact
        hackmyresume build resume/resume.json to resume/resume.pdf -t fresh/themes/compact -p phantom
        
    # Add & Commit resume changes
    - name: Add & Commit resume changes
      uses: EndBug/add-and-commit@v4.4.0
      with:
        add: resume.pdf readme.txt
        message: Update resume files

