# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: 
      - master
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup Node.js environment
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      
    # Install the latest version of HackMyResume with NPM:
    - name: Install HackMyResume with NPM
      run: npm install hacksalot/hackmyresume#dev -g
    
    # Install latest version of wkhtmltopdf & wkhtmltoimage
    - name: Install wkhtmltopdf & wkhtmltoimage
      run: |
        pushd /tmp
        sudo apt update
        sudo apt -y install wget
        wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
        sudo apt -y install ./wkhtmltox_0.12.6-1.focal_amd64.deb
        sudo apt -f install
        wkhtmltopdf --version
        wkhtmltoimage --version
        popd

